/** @type {import('tailwindcss').Config} */

module.exports = {
  mode: 'jit',
  content: [
    "./components/**/*.vue",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.js",
    "./nuxt.config.js",
    "./assets/dynamicTailwindClasses/classes.txt",
  ],
  safelist: [
    'bg-lightRed',
    'bg-red/25',
    'text-grey',
    'bg-grey/25',
    'bg-white',
    'bg-green',
    'bg-blue',
    'border-black',
    'border-darkOffwhite',
    'border-2',
    'h-6',
  ],

  theme: {
    extend: {
      fontFamily: {
        'heading': ['Heading, serif'],
        'body': ['Inter, sans-serif'],
      },
      scale: {
        '25': '.25',
        '80': '.8',
      },
      boxShadow: {
        'edit': 'inset 0 0 0 2px #E6A7F1',
      },
      colors: {
        offwhite: "#f8f8f8",
        darkOffwhite: "#eee",
        lightGrey: "#F0F1EC",
        grey: "#999",
        darkGrey: "#666",
        black: "#1E1E2A",
        blackHighlight: "#082C3E",
        lightOrange: "#FFC9BD",
        orange: "#FBB03B",
        sand: "#CB8B65",
        lightGreen: "#38f3af",
        grassGreen: "#C3CC59",
        // green: '#1edf99',
        lilac: "#C792EA",
        darkLilac: "#651273",
        green: "#44B57A",
        lightYellow: "#FED600",
        yellow: "#FCB900",
        darkYellow: "#FFA617",
        neonYellow: "#ddff33",
        darkNeonYellow: "#B7D231",
        lightRed: "#F2ADAD",
        red: "#F05C4D",
        darkRed: "#DD3A3A",
        lightBlue: "#72D2FF",
        blue: "#48BAFF",
        darkBlue: "#2F3676",
        blueGrey: "#F3F7FA",
      },
    },
  },
  plugins: [],
  container: {},
};
